# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
          # If you use workspaces, consider: '**/yarn.lock'
          cache-dependency-path: yarn.lock

      # Yarn 3/4 is provided via Corepack on the runner; enable it.
      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install dependencies (Yarn)
        run: |
          if [ -f .yarnrc.yml ]; then
            # Yarn Berry (v3/v4)
            yarn install --immutable
          else
            # Yarn Classic (v1)
            yarn install --frozen-lockfile
          fi

      - name: Build
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Adjust if your build outputs elsewhere
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4